modLoader="kotlinfml" #mandatory
loaderVersion="[2,)" #mandatory (24 is current forge version)
issueTrackerURL="http://github.com/jglrxavpok/Moar-Boats/issues" #optional
license="All rights reserved"

[[mods]] #mandatory
modId="moarboats" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Moar Boats" #mandatory
updateJSONURL="https://raw.githubusercontent.com/jglrxavpok/Moar-Boats/master/updateCheck.json" #optional
displayURL="https://www.curseforge.com/minecraft/mc-mods/moar-boats" #optional
logoFile="logo.png" #optional
credits="DYColdWind for the Chinese translation" #optional
authors="jglrxavpok" #optional
description='''
Adds more uses to boats!
'''

[[dependencies.moarboats]]
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[32,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.moarboats]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.2]"
    ordering="NONE"
    side="BOTH"
